# input_dir: "../../../dataset/ogbn_products_new/balanced_training_samples/"
input_dir: "/home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/ogbn_products_new/balanced_out_degree/"
graph_name: "products"
in_channels: 100
hidden_channels: 256
out_channels: 47
num_layers: 3
dropout: 0.5
lr: 0.01
weight_decay: 0.0
num_epochs: 250
random_seed: 42
patience: 100
layer_norm: true
w_att: 0.0005
w_fc2: 0.0005
w_fc1: 0.0005
lr_fc: 0.02
lr_att: 0.02
combine_type: cat
is_async: false