input_dir: "/home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/ogbn_arxiv_new/"
graph_name: "arxiv"
in_channels: 128
hidden_channels: 256
out_channels: 40
num_layers: 3
dropout: 0.5
lr: 0.01
weight_decay: 0.0
num_epochs: 500
random_seed: 42
patience: 100
layer_norm: true
w_att: 0.0005
w_fc2: 0.0005
w_fc1: 0.0005
lr_fc: 0.02
lr_att: 0.02
combine_type: cat
is_async: false
use_defined_ddp: false