# input_dir : "../../dataset/proteins/balanced_training_samples/"
input_dir : "../../dataset/proteins/balanced_out_degree/"
graph_name : "proteins"
model_name : "sage"
in_channels : 128
hidden_channels : 256
out_channels : 256
num_layers : 3
dropout : 0.5
lr : 0.01
weight_decay : 0.0
num_epochs : 200
random_seed : 0
is_async : true
assign_period : 50
