input_dir: "/home/chenzhuang/super_gnn/data/ogbn_products/"
graph_name: "ogbn_products"
model_name: "sage"
# model_name: "gcn"
in_channels: 100
hidden_channels: 256
out_channels: 47
num_layers: 3
dropout: 0.5
lr: 0.01
weight_decay: 0.0
num_epochs: 250
random_seed: 0
is_async: true
assign_period: 50
norm_type: "LayerNorm"
