# input_dir: "../../../dataset/ogbn_papers100M_new/balanced_training_samples/"
# input_dir: "/home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/ogbn_papers100M_new/balanced_out_degree/"
input_dir: "/home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/ogbn_papers100M_new/add_symmetric/"
graph_name: "papers100M"
model_name: "sage"
in_channels: 128
hidden_channels: 256
out_channels: 172
num_layers: 3
dropout: 0.5
lr: 0.001
weight_decay: 0.0
num_epochs: 200
random_seed: 0
is_async: false
assign_period: 50
norm_type: LayerNorm
