# input_dir: "../../../dataset/reddit/balanced_training_samples/"
input_dir: "/home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/reddit/balanced_out_degree/"
graph_name: "reddit"
model_name: "sage"
# model_name: "gcn"
in_channels: 602
hidden_channels: 256
out_channels: 41
num_layers: 3
dropout: 0.5
lr: 0.01
weight_decay: 0.0
num_epochs: 250
random_seed: 0
is_async: false
assign_period: 50
norm_type: "LayerNorm"
